# ------------------------------------------------------------------------------
# Don't set Err File Permissions to MQ default
# ------------------------------------------------------------------------------
Filesystem:
   ValidateAuth=No

