#!/bin/bash 

OPT=$1 

case $OPT in
  "")
    if [[ "$(id -un)" != "mqm" ]] 
    then
      echo "  executing with user \'$(id -un)\' user" 
      echo "  use --restricted-user " 
      exit  1
    fi
  ;;
  "--restricted-user")
    USER=$(id -un)
    if [[ "$USER" != "$2" ]] 
    then
      echo "  executing with user \'$(id -un)\' user" 
      echo "  not with restricted user \'$2\' "
      exit 1
    fi
     id -Gn $USER | tr " " "\n" | grep -q "^mqm$"
     rc=$?
     if [[ $rc -ne 0 ]]
     then
       echo "  restricted user must be member of mqm group"
       exit 1
     fi
  ;;
  "*")
    echo "  unknwon attribte"
    exit  1
  ;; 
esac

[ -d $HOME/.bin          ] || mkdir $HOME/.bin
[ -d $HOME/bin           ] || mkdir $HOME/bin
[ -d $HOME/system        ] || mkdir $HOME/system
[ -d $HOME/cfg           ] || mkdir $HOME/cfg 
[ -d $HOME/etc           ] || mkdir $HOME/etc 
[ -d $HOME/dlq.rules     ] || mkdir $HOME/dlq.rules
[ -d /home/mqm/dlq.rules ] || mkdir /home/mqm/dlq.rules    
[ -d $HOME/qmgr.profile  ] || mkdir $HOME/qmgr.profile
[ -d $HOME/.profile.d    ] || mkdir $HOME/.profile.d 
[ -d $HOME/.config/systemd/user ] || mkdir -p $HOME/.config/systemd/user 

touch $HOME/.profile.d/empty
cp user.profile   $HOME/.profile 
cp uc4.logging    $HOME/.profile.d/disable.uc4.logging
cp editrc         $HOME/.editrc

cp _QMGR_.profile $HOME/qmgr.profile
cp user@.service  $HOME/system
cp mq.ctrl.ksh    $HOME/bin
cp xapass.pl      $HOME/bin 
cp strmqm         $HOME/.bin 
cp endmqm         $HOME/.bin 
cp service.env    /var/mqm/
cp qm.ssl.ini     $HOME/cfg
cp qm.fs.ini      $HOME/cfg
cp qm.chl.ini     $HOME/cfg
cp cert.tar       $HOME/cfg
cp dlh.ksh        /home/mqm/bin
cp version        $HOME/etc/mqcfg.version

# ----------------------------------------------------------
# cp mq@.service $HOME/.config/systemd/user is not ok
# adjust mqm to real user with pearl
# ----------------------------------------------------------
perl -e 'open IN, $ARGV[0]; while(<IN>) {s/\/mqm\//\/$ARGV[1]\//; print $_;}' mq@.service $(id -un) > $HOME/.config/systemd/user/mq@.service
systemctl --user daemon-reload

exit 0
