#!/bin/bash 

OPT=$1 

case $OPT in
  "")
    if [[ "$(id -un)" != "mqm" ]] 
    then
      echo "  executing with user \'$(id -un)\' user" 
      echo "  use --restricted-user " 
      exit  
    fi
  ;;
  "--restricted-user")
    USER=$(id -un)
    if [[ "$USER" != "$2" ]] 
    then
      echo "  executing with user \'$(id -un)\' user" 
      echo "  not with restricted user \'$2\' "
      exit
    fi
     id -Gn $USER | tr " " "\n" | grep -q "^mqm$"
     rc=$?
     if [[ $rc -ne 0 ]]
     then
       echo "  restricted user must be member of mqm group"
       exit ;
     fi
  ;;
  "*")
    echo "  unknwon attribte"
    exit 
  ;; 
esac

[ -d $HOME/.bin         ] || mkdir $HOME/.bin
[ -d $HOME/bin          ] || mkdir $HOME/bin
[ -d $HOME/system       ] || mkdir $HOME/system
[ -d $HOME/cfg          ] || mkdir $HOME/cfg 
[ -d $HOME/qmgr.profile ] || mkdir $HOME/qmgr.profile
[ -d $HOME/.profile.d   ] || mkdir $HOME/.profile.d 
[ -d $HOME/.config/systemd/user ] || mkdir -p $HOME/.config/systemd/user 

touch $HOME/.profile.d/empty
cp user.profile   $HOME/.profile 
cp uc4.logging    $HOME/.profile.d/disable.uc4.logging
cp editrc         $HOME/.editrc
cp mq@.service    $HOME/.config/systemd/user 
cp _QMGR_.profile $HOME/qmgr.profile
cp user@.service  $HOME/system
cp mq.ctrl.ksh    $HOME/bin
cp xapass.pl      $HOME/bin 
cp strmqm         $HOME/.bin 
cp endmqm         $HOME/.bin 
cp service.env    /var/mqm/
cp qm.ssl.ini     $HOME/cfg
cp qm.fs.ini      $HOME/cfg
