# ------------------------------------------------------------------------------
# swithc off OCSPC check
# must be included on every queue manager
# ------------------------------------------------------------------------------
SSL:
   OCSPCheckExtensions=No
